// <auto-generated />
namespace ToDoListApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsComplete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsComplete));
        
        string IMigrationMetadata.Id
        {
            get { return "201602031408499_IsComplete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
